logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  error:
    whitelabel:
      enabled: true
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: data-source
    url: jdbc:mysql://localhost:3306/expense_planner_db_uat?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    password: anshuSoft
    username: root
  jackson:
    date-format: MMMM dd yyyy / HH:mm
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    host_address: host_address
    username: write2deepeshkumar@gmail.com
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    protocol: smtp
  mvc:
    throw-exception-if-no-handler-found: true

security:
  public-pattern: /api/public/**
  auth:
    username: user_name
    url: http://localhost:9090/oauth/check_token
    client_id: Mobile
    client_password: test
    connection_timeout: 60
    read_timeout: 60
    whitelist: >
      /,
      /v2/api-docs,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**

swagger:
  host:
    address: localhost:8080
    path: /
  api:
    name: Planner Api Documentation
    version: v1
  contact:
    name: Deepesh Malviya
    url: https://www.appkode.com
    email: deepeshkumar03@gmail.com

